services:
  - type: web
    name: lecturepulse-api
    runtime: node
    rootDir: BackEnd
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUBLIC_BASE_URL
        value: https://lecturepulse-api-tanishk.onrender.com
      - key: DATABASE_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_KEY
        sync: false
