export {
  SUPPORTED_AUDIO_EXTENSIONS,
  createTranscript,
  getTranscriptByLectureId,
  isSpeechRecognitionSupported,
  isOpenAiConfigured,
  isTranscriptionConfigured,
  isTranscribableMedia,
  isTranscribableMediaUrl,
  stageToStep,
  transcribe,
  transcribe as transcribeLectureAudio,
  updateTranscript,
  type TranscriptionProgress,
  type TranscriptionStage,
  type TranscriptionStep,
} from '@/services/transcriptionService'
